### ISSUE TITLE
Termara jump hotkey

### ISSUE THREAD

**Issue by DimlyMoonbeam** [Amazinite/Enigma-Corp#15]
When in Termara system, pressing 'j' in the map to cycle through jump solutions only targets Enigma system.  Suhail is not indicated as a target pressing 'j'.

**Comment by Amazinite** [comment]
That might be a bug from a77a8d1. I'll check it out tomorrow morning.

**Comment by Amazinite** [comment]
Found the bug; the "link Suhail" line for the Termara system got accidentally tabbed in when I created the belt line, so while Suhail is linked to Termara, Termara is not linked back to Suhail. (Links have to go both ways to work properly.)

**Comment by Amazinite** [comment]
Weird. On my phone it showed an extra tab, but when I pull it up now, there's no problem. Also, I can't replicate this with Suhail, but I am getting it where it won't allow me to cycle to Enigma.

**Comment by DimlyMoonbeam** [comment]
I don't see extra tabs on my phone, nor my laptop.  I'm not too experienced with map files, but both link lines look OK at my first glance.  I'll try retyping those lines when I get home this evening.

**Comment by Amazinite** [comment]
I think they are fine. This may be a problem with the game itself and not my mod. I'd have to test this in other locations where mod systems link with vanilla systems, though.

**Comment by DimlyMoonbeam** [comment]
Fixed it by removing the decimal in line 1544 from `pos -757 -411.5` to `pos -757 -412`.  Tab depth remained the same.  This is the position of the Termara system.

Edit\* I have no idea how to upload a fixed file on my own :(
Edit*\* I made a pull request, I think I did it the proper way?
