### ISSUE TITLE
Quarg hostile to Enigma Corp

### ISSUE THREAD

**Issue by DimlyMoonbeam** [Amazinite/Enigma-Corp#19]
So, in my new character (so I'm still in my initial ship), I just started doing the intro FW missions, and I was over at Tarazed to pick up some jobs.  I picked up an escort job, and when I left the planet, a Quarg ship flew by and absolutely murdered an entire fleet of Enigma Corp ships.

While it was really funny to watch, I wonder if this is intended or due to some unforeseen interaction between Quarg and when (possibly) the Enigma Corp ships fired on the pirate ship in system from my escort job.  It all happened so fast, so I do not know if the EC ships fired on the pirate or not.

Edit\* So I stayed in system for a while, and the Quarg keeps murdering the EC ships.  Wish I had a video for you.

**Comment by Amazinite** [comment]
Quarg hating EC is intentional, although I should actually stop EC fleets from spawning in the systems near Quarg space because of that, or at least make it rare for them to spawn.

**Comment by DimlyMoonbeam** [comment]
Ah, I see.  That's what I get for having yet to reach the EC story line.

**Comment by Amazinite** [comment]
The story so far does little in the way of explaining why anyways. But for right now, the Enigma Corp is enemies with almost all alien factions. In the future when I develop the story more, they will likely start out friendly but become hostile over time.
