### ISSUE TITLE
Much more than the Grav Wave Gun

### ISSUE THREAD

**Issue by Alkallid** [Amazinite/Enigma-Corp#2]
You wrote generators instead of generates.

**Comment by Alkallid** [comment]
Whenever you reference another weapon, like the Sidewinder, capitize it. Several times you need to capitalize Meteor ot something.

**Comment by Alkallid** [comment]
For the flux- "This is the Sidewinder's version..." You should imply better "the Sidewinder of Enigma Corp's rip-offs," if the above weapon was the Meteor.

**Comment by Alkallid** [comment]
Not important because of the description formatting, but the Clux Mine Placer has a double space.

**Comment by Amazinite** [comment]
Mate, you're blowing my phone up.

**Comment by Amazinite** [comment]
For the Flux missile launcher, the description is right how it is. "This is the Sidewinder's version of the Hellfire." It's saying how the Flux missile launcher is to the Sidewinder as the Hellfire is to the Meteor.

**Comment by Alkallid** [comment]
Aye, seems good then.

**Comment by Alkallid** [comment]
"That will explode when an enemy that gets too close-"
Typhoon Mine

**Comment by Amazinite** [comment]
If you're gonna keep finding more, I'll just wait here. :)

**Comment by Alkallid** [comment]
Actually, for all mine placers you did that.

**Comment by Amazinite** [comment]
Well that's cool.

**Comment by Alkallid** [comment]
Goddammit I'm a slave now

**Comment by Amazinite** [comment]
xD
They all had the same double space as well. Guess I copied and pasted some stuff.

**Comment by Alkallid** [comment]
Repair Gun- "The Deep _as_"

**Comment by Alkallid** [comment]
Did you need to specify _electric_ energy for the transferer?

**Comment by Amazinite** [comment]
I don't know, could have been food energy.

**Comment by Alkallid** [comment]
You make it sound like the _Quarg_ reverse engineered as a solution.


I'm finding something in every weapon, bruh, you need to up your Engrish.

**Comment by Amazinite** [comment]
Jesus, now I'm feeling like the slave.

**Comment by Alkallid** [comment]
Super-heated should be hyphenated, and shields should be plural.
Plasmathrowaaaa

**Comment by Alkallid** [comment]
Again, capitalize Arc Discharger, and maybe rework the whole description. Add "will most likely disable-" and "-the shields of bigger ships."

**Comment by Amazinite** [comment]
Don't freak out on the Flux Torpedo description, I just changed it.

**Comment by Amazinite** [comment]
Also capitalized all the weapon names.

**Comment by Alkallid** [comment]
Because everyone else also has bad literacy. Even LocalGod.

**Comment by Amazinite** [comment]
This is true.

**Comment by Alkallid** [comment]
Unfortunately so.

**Comment by Amazinite** [comment]
Are you going to go through all of the files, because it's one in the morning for me right now. I'll just commit what I've done in the weapons file and fix the rest in the morning.

**Comment by Alkallid** [comment]
Also, is ther anyone else besides Grapefruit-on-elf-head who's got their mod on Git? My ELA skill is rising.

**Comment by Alkallid** [comment]
Like Friendly?

**Comment by Alkallid** [comment]
Yeah. I'll find what I can. 
Ehat are you doing up so late?

**Comment by Amazinite** [comment]
Takarada has Alphean Boolean on here.

**Comment by Amazinite** [comment]
It's Saturday, why not be up late?

**Comment by Amazinite** [comment]
Well, was Saturday.

**Comment by Alkallid** [comment]
I know. His Steam pic is Will Ferrel with an orange on his head now.

**Comment by Amazinite** [comment]
[Here](https://github.com/OmegaZanicus/endless-sky-plugins) is OmegaZanicus's page. Not sure if he actually does anything on it though.

edit: nope.

**Comment by Alkallid** [comment]
Pfft, you did _not_ capitalize them all. Now shut up and sleep or read a dictionary.

**Comment by Amazinite** [comment]
I did, but I didn't push the commit through yet.

**Comment by Amazinite** [comment]
Committed.

**Comment by Amazinite** [comment]
Now I'mma go to sleep. Good luck to thee finding my many typos.

**Comment by Alkallid** [comment]
Derpy's mod

Shrapnel Cannon also needs to hyphenate super-heated.

OH NO YOU DIDN'T! THE FUEL ROD LAUNCHER WASN'T CAPITALIZED, YOU *****************************************
Also, you repeated the word cause. The second description seems fragmented, -like- because you half-assed it.
And you forgot "Brought to you by..."


Flux Topedo
It's either 'The Deep's' or 'Deep Sky's,' not the Deep Sky's.
Built by _the_ Syndicate or Syndicated Systems. 
"Enemy ships" is repetitive.
Short-circuits hyphenated.
Capitalize

Many of your descriptions repeat enemy ships, massive heat/ion, specifically, whatever.

Forge
Railgun one word.
High-power
Do reload periods.

I should consider rewriting many of these if you allowed.

Shouldn't the MDS reload be two _hundred?_

Seeker
"truely" You gotta be kidding me
"...but what it does is truly..." Better
"an extremely fast speeds"

EMP?

**Comment by Alkallid** [comment]
Capitalize Sentry and all names here on out
_And_ a turret strapped... Alredy used with
"Any turret out want" _dies_
The damn period.....................

Viper
Why _the_ Enigma Corp?
Don't keep repeating, use they, their, it
Just say ammo

Rattlesnake
Just say their missiles
I don't think monopolize was the right word

King
End has exclamation and full stop

Aegis is boring, repeated warship

Orca
It's freight, not freighting
I see you pressed m instead of ,

You referenced the Queen at the end, advertising the wrong ship. Also, false. Also, say sister ship.
Also, 69

Stardian
Just VIP
Unlucky enough to get caught

oh my god as i do this my own english is deteriorating

Rework the Hawk

Overused true and in

**Comment by Alkallid** [comment]
Why am I doing this but,

Galactic Map
"This data chips"
Bad sentencing, just say pirates stole a bunch of maps or something

PW
No limited to
cthulhu
I think you mean capitalized end of days
well-being

ExFP

-500 shields and hull

Expansions
_beter_ use
_pout/wonder/sigh_ no more!
more or bigger

Cap Jump Drive

**Comment by Alkallid** [comment]
heavy water contradicts itself- same density or not?!

opposed*
...than a normal fusion

_a_ black hole
compared to other generators

No to the batteries, atomic, really?

No _for_ when...

heat sink is false, that's what mass does

**Comment by Alkallid** [comment]
Known to man for the engines.

**Comment by Alkallid** [comment]
All of these I'm wastin time on. If I have to I will force you to create actual liable outfits so my words and time aren't wasted.

**Comment by Alkallid** [comment]
h2h

burst of plasma instead

plural versions
high-speed

high-energy
low-energy
ball-bearing shot

craftily designed

reaction _time_

**Comment by Alkallid** [comment]
I'm not bothering with ammo and cap increases.

**Comment by Alkallid** [comment]
Even though they still suck.
And capitalize...

**Comment by Alkallid** [comment]
smuggler's best friend

hitpoints to armor strength

smaller ships to interceptors

"hipooitns" to shields

capitals to heavy warships

most massive to most advanced capital-class


An E class for Light Freighters and Transports, Between F and D

Boost all by 50% so E is balanced for right size and strength, Probably around 1250

F to Fighters

D to Interceptors

C to Light Warships and Heavy Feighters

B to Medium Warships

A to Heavy Warships

S to Advanced Capital Classes


all this armor reinforcement


all this shield boosting

**Comment by Amazinite** [comment]
For the Rattlesnake, I really didn't know what word to use. I just looked to my left and saw a monopoly box.

**Comment by Amazinite** [comment]
> reaction time

Reaction time and reaction speed are the same thing and can be used interchangeably, as long as you make sure to change other stuff accordingly.
i.e. "high reaction time" = "low reaction speed"

**Comment by Amazinite** [comment]
I'm deleting comments of stuff I've done.

**Comment by Amazinite** [comment]
Deleting ones I finished

**Comment by Amazinite** [comment]
b8b0dca

**Comment by Alkallid** [comment]
G'day m8

**Comment by Amazinite** [comment]
You want to do it all over again and check my new descriptions?
Only H2H stuff done right now.
