### ISSUE TITLE
Pirates Spawning out of Enigma Prime

### ISSUE THREAD

**Issue by themightygrunt** [Amazinite/Enigma-Corp#21]
basically what it says, As Enigma Has Pirates, they tend to spawn out of Enigma Prime or Meridan, kinda confusing, as it looks like my fleet randomly attacks Enigma dudes

**Comment by Amazinite** [comment]
Sounds like a personal problem (and an old version).

**Comment by themightygrunt** [comment]
Odd, i have the latest one on Github, (Unless you've updated since March 29th)
