### ISSUE TITLE
Mission Wording

### ISSUE THREAD

**Issue by Alkallid** [Amazinite/Enigma-Corp#3]
Missing colon at the fisrt statuon announcement

**Comment by Alkallid** [comment]
Also missing period when "... a man walks up to you"
At the first escort

**Comment by Alkallid** [comment]
Yet again after "...hurry up"

**Comment by Alkallid** [comment]
Ehrn you finish it, don't do captain of npc ship.
Fo captain of the convoy

**Comment by Alkallid** [comment]
Does it even work with 3 different fleet names?

**Comment by Alkallid** [comment]
"Seek it down"
That's not how it works

**Comment by Alkallid** [comment]
Shouldn't it be return it to <source>?

**Comment by Alkallid** [comment]
<source>

**Comment by Alkallid** [comment]
<Source >

**Comment by Alkallid** [comment]
<Source

**Comment by Alkallid** [comment]
Spam much

**Comment by Alkallid** [comment]
Just "that would be in your best interests to accept."

**Comment by Alkallid** [comment]
The Syndicate _employees_ gratefully

**Comment by Alkallid** [comment]
Ownernof a ship and weapons develop_ment_...

**Comment by Amazinite** [comment]
I'll do this,,. Eventually.

**Comment by Alkallid** [comment]
Noooo... I did, but I didn't do it right... An hour down the drain.

**Comment by Amazinite** [comment]
> Ownernof a ship and weapons develop_ment_...

wtf are you talking about?

**Comment by Amazinite** [comment]
I've done everything but that last one, as I have no idea what you mean by that.

**Comment by Alkallid** [comment]
It should be development <noun like corporation>

**Comment by Amazinite** [comment]
Where at though?

**Comment by Amazinite** [comment]
Found it.

**Comment by Alkallid** [comment]
Shit, I put the mouths around it.

**Comment by Alkallid** [comment]
https://drive.google.com/file/d/0B2mrVBjx_V9TWGpMUUZORkw2Q3M/view?usp=drivesdk

**Comment by Alkallid** [comment]
Soon-to-be me.
